#  Template Java Spring Boot App for Elastic Beanstalk

#  This template allows you to deploy your application as code using AWS Elastic Beanstalk.
#  The workflow allows validate, linting and security scans on feature branches (as well as master).
#  The Spring Boot App will be validated and deployed after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/aws-elasticbeanstalk-deploy/src/master/README.md

image: gradle:8.10.1-jdk17

definitions:
  caches:
    zip: /usr/bin
    maven-local: ~/.m2
    gradle: ~/.gradle
  services:
    docker:
      memory: 2048

pipelines:    
  branches:
    main:
      - step:
          name: Build Local Dependencies Kickstart
          caches:
            - maven-local
          script:
            - # Download and install Maven 3.8.3
            - wget https://archive.apache.org/dist/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
            - tar -xzf apache-maven-3.8.3-bin.tar.gz
            - export M2_HOME=$(pwd)/apache-maven-3.8.3
            - export PATH=$M2_HOME/bin:$PATH
            - # Verify Maven version
            - mvn --version
            - git clone git@bitbucket.org:esentri/nitrox-kickstart.git
            - cd nitrox-kickstart
            - git checkout feature/roaster
            - mvn clean install
            - cd ..
            - git clone git@bitbucket.org:esentri/diagram-viewer-plugin.git
            - cd diagram-viewer-plugin
            - gradle clean build publishToMavenLocal
            - cd ..
            - git clone git@bitbucket.org:esentri/diagram-viewer-generator-plugin.git
            - cd diagram-viewer-generator-plugin
            - gradle clean build publishToMavenLocal
            - cd ..
            - ls -R ~/.m2/repository/io/domainlifecycles
          artifacts:
            - ~/.m2/repository/**
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Download bash Packages
          caches:
            - zip
          script:
            - apt-get update
            - apt-get install -y zip
      - step:
          name: Build & Test
          caches:
            - maven-local
            - gradle
            - zip
          services:
            - docker
          script:
            - ls -R ~/.m2/repository/io/domainlifecycles
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - export BUILD_PROFILE=$BUILD_PROFILE
            - gradle clean build -Pvaadin.productionMode
            - zip -r application.zip .platform
            - zip -j application.zip build/libs/diagram-viewer-0.0.1-SNAPSHOT.jar
          after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
                variables:
                  DEBUG: "true"
          artifacts:
            - application.zip
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                APPLICATION_NAME: 'diagram-viewer'
                ENVIRONMENT_NAME: 'diagram-viewer-environment'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: '0.0.1-$BITBUCKET_BUILD_NUMBER'
