buildscript {
	repositories {
		mavenCentral()
		maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
		maven { setUrl("https://repo.spring.io/milestone") }
	}
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'com.vaadin'
	id 'jacoco'
}

group = 'io.domainlifecycles'
version = '0.0.1-SNAPSHOT'

ext {
	set('vaadinVersion', "24.8.6")
	javaDockerVersion = "3.4.0"
	dlcVersion = "2.4.1"
	classGraphVersion = "4.8.163"
	isInternal = System.getenv('IS_BUILD_PROFILE_INTERNAL')
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	mavenLocal()
	maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
	maven { setUrl("https://repo.spring.io/milestone") }
	maven { setUrl("https://maven.vaadin.com/vaadin-addons") }
}

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
}

tasks.named('bootJar') {
	enabled = true
}

dependencies {
	implementation "io.github.classgraph:classgraph:${classGraphVersion}"
	implementation "com.vaadin:vaadin-spring-boot-starter"
	implementation "org.springframework.boot:spring-boot-starter-data-jpa"
	implementation ('org.postgresql:postgresql')
	testImplementation ('org.testcontainers:postgresql:1.20.6')
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation ('com.okta.spring:okta-spring-boot-starter:3.0.7')
	implementation "com.github.docker-java:docker-java-core:${javaDockerVersion}"
	implementation "com.github.docker-java:docker-java-transport-httpclient5:${javaDockerVersion}"
	implementation 'com.flowingcode.vaadin.addons:zoomist-addon:1.0.1'
	implementation 'org.vaadin.addons.taefi:toggle-button-group:2.2.0'
	implementation "io.domainlifecycles:mirror:${dlcVersion}"
	implementation "io.domainlifecycles:diagram-viewer-plugin:1.0"
	implementation "io.domainlifecycles:domain-diagrammer:${dlcVersion}"
	if(isInternal){
		println "INTERNAL PROFILE ACTIVE"
		implementation("io.domainlifecycles:diagram-viewer-generator-plugin:1.0")
	}
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation "org.springframework.boot:spring-boot-starter-test"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "com.vaadin:vaadin-bom:${vaadinVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

test {
	finalizedBy jacocoTestReport
}
jacocoTestReport {
	dependsOn test
	reports {
		xml.required = false
		csv.required = false
		html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
					"**/webapp/*"
			])
		}))
	}
}