plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.vaadin' version '24.6.2'
}

group = 'io.domainlifecycles'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	mavenLocal()
	maven {
		url = uri("https://maven.vaadin.com/vaadin-addons")
	}
}

ext {
	set('vaadinVersion', "24.6.2")
	javaDockerVersion = "3.4.0"
}

tasks.named('bootJar') {
	enabled = true
}

dependencies {
	implementation ('org.springframework.boot:spring-boot-starter-web'){
		exclude group: "commons-logging"
		exclude group: "org.slf4j"
		exclude group: "ch.qos.logback"
	}
	implementation ('com.vaadin:vaadin-spring-boot-starter'){
		exclude group: "commons-logging"
		exclude group: "org.slf4j"
		exclude group: "ch.qos.logback"
	}
	implementation ('org.springframework.boot:spring-boot-starter-data-jpa') {
		exclude group: "commons-logging"
		exclude group: "org.slf4j"
		exclude group: "ch.qos.logback"
	}
	implementation 'org.postgresql:postgresql'
	implementation ('org.springframework.boot:spring-boot-starter-actuator') {
		exclude group: "commons-logging"
		exclude group: "org.slf4j"
		exclude group: "ch.qos.logback"
	}
	implementation ('com.okta.spring:okta-spring-boot-starter:3.0.6') {
		exclude group: "commons-logging"
		exclude group: "org.slf4j"
		exclude group: "ch.qos.logback"
	}
	implementation "com.github.docker-java:docker-java-core:${javaDockerVersion}"
	implementation "com.github.docker-java:docker-java-transport-httpclient5:${javaDockerVersion}"
	implementation 'com.flowingcode.vaadin.addons:zoomist-addon:1.0.1'
	implementation 'io.domainlifecycles:mirror:2.1.0'
	implementation 'io.domainlifecycles:domain-diagrammer:2.1.0'
	implementation("io.domainlifecycles:kickstart-generator:1.0.3"){
		exclude group: "commons-logging"
		exclude group: "ch.qos.logback"
	}
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "com.vaadin:vaadin-bom:${vaadinVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}