import dev.yumi.gradle.licenser.task.CheckLicenseTask

buildscript {
	repositories {
		mavenCentral()
		maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
		maven { setUrl("https://repo.spring.io/milestone") }
	}
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'com.vaadin'
	id 'jacoco'
	id 'checkstyle'
	id 'dev.yumi.gradle.licenser' version '2.2.2'
}

group = 'io.domainlifecycles'
version = '0.2'

ext {
	set('vaadinVersion', "24.8.6")
	javaDockerVersion = "3.4.0"
	dlcVersion = "3.4.1-backwardflowtest"
	classGraphVersion = "4.8.163"
	isInternal = System.getenv('IS_BUILD_PROFILE_INTERNAL')

	postgresImage = "postgres:16"
	krokiImage = "yuzutech/kroki"
	appImage = "domainlifecycles/diagram-viewer:${project.version}"
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	mavenLocal()
	maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
	maven { setUrl("https://repo.spring.io/milestone") }
	maven { setUrl("https://maven.vaadin.com/vaadin-addons") }
}

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
}

bootBuildImage {
	imageName = appImage
	vaadin {
		productionMode = true
	}
}

tasks.named('bootJar') {
	mainClass = "io.domainlifecycles.diagramviewer.DiagramViewerApplication"
	enabled = true
}

dependencies {
	implementation "io.github.classgraph:classgraph:${classGraphVersion}"
	implementation "com.vaadin:vaadin-spring-boot-starter"
	implementation "org.springframework.boot:spring-boot-starter-data-jpa"
	implementation ('org.postgresql:postgresql')
	testImplementation "org.testcontainers:junit-jupiter:1.20.6"
	testImplementation "org.testcontainers:postgresql:1.20.6"
	implementation 'org.apache.xmlgraphics:batik-transcoder:1.17'
	implementation 'org.apache.xmlgraphics:batik-codec:1.17'
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation ('com.okta.spring:okta-spring-boot-starter:3.0.7')
	implementation "com.github.docker-java:docker-java-core:${javaDockerVersion}"
	implementation "com.github.docker-java:docker-java-transport-httpclient5:${javaDockerVersion}"
	implementation 'com.flowingcode.vaadin.addons:zoomist-addon:1.0.1'
	implementation 'org.vaadin.addons.taefi:toggle-button-group:2.2.0'
	implementation "io.domainlifecycles:mirror:${dlcVersion}"
	implementation "io.domainlifecycles:mirror-serialization-jackson2:${dlcVersion}"
	implementation "io.domainlifecycles:static-analysis:${dlcVersion}"
	implementation "io.domainlifecycles:static-analysis-serialization-jackson2:${dlcVersion}"
	implementation "io.domainlifecycles:diagram-viewer-plugin:1.2"
	implementation "io.domainlifecycles:domain-diagrammer:${dlcVersion}"
	if(isInternal){
        println "INTERNAL PROFILE ACTIVE"
		implementation("io.domainlifecycles:diagram-viewer-generator-plugin:1.3")
	}
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation "org.springframework.boot:spring-boot-starter-test"
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.mockito:mockito-core'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "com.vaadin:vaadin-bom:${vaadinVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
	exclude '**/*_ITest.class'
}

plugins.withId('checkstyle') {
	checkstyle {
		toolVersion = '10.12.4'
		configFile = rootProject.file('./checkstyle/checkstyle.xml')
		ignoreFailures = true
		showViolations = true

		checkstyleMain.source = "src/main/java"
	}
}

plugins.withId('dev.yumi.gradle.licenser') {
	checkLicenseMain.enabled = true
	checkLicenseTest.enabled = false
	license {
		rule(file("./copyright/HEADER"))
		include("**/*.java")
	}
	tasks.named("checkLicenseMain", CheckLicenseTask).configure {
		// ConfigurableFileCollection supports setFrom(...)
		sourceFiles.setFrom(
				sourceFiles.filter { f -> !f.name.endsWith(".svg") }
		)
	}

}

tasks.register('integrationTest', Test) {
	group = 'verification'
	description = 'Runs integration tests'

	testClassesDirs = sourceSets.test.output.classesDirs
	classpath = sourceSets.test.runtimeClasspath

	include '**/*_ITest.class'

	useJUnitPlatform()

	maxParallelForks = 1
	forkEvery = 1
	jvmArgs '-Xmx1536m'

	shouldRunAfter test
}

tasks.named("check") {
	dependsOn(tasks.named("integrationTest"))
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = false
		csv.required = false
		html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
					"**/webapp/*"
			])
		}))
	}
}

def containerDir = layout.buildDirectory.dir("container")

tasks.register("pullBaseImages", Exec) {
	group = "container"
	commandLine "sh", "-lc", """
    set -e
    docker pull ${postgresImage}
    docker pull ${krokiImage}
  """
}

tasks.register("saveContainerImages", Exec) {
	group = "container"
	dependsOn tasks.named("bootBuildImage")
	dependsOn tasks.named("pullBaseImages")

	doFirst { containerDir.get().asFile.mkdirs() }

	commandLine "sh", "-lc", """
    set -euo pipefail

    docker save '${appImage}' '${postgresImage}' '${krokiImage}' \
      -o '${containerDir.get().asFile}/diagram-viewer-images.tar'
  """
}

tasks.register("buildContainerImages", Tar) {
	group = "container"
	dependsOn tasks.named("saveContainerImages")

	archiveFileName = "diagram-viewer-bundle.tar.gz"
	destinationDirectory = containerDir.get().asFile
	compression = Compression.GZIP

	from("docker/run/docker-compose.yml") {
		into(".")
	}
	from(containerDir.map { it.file("diagram-viewer-images.tar") }) {
		into(".")
	}
}
