vaadin.launch-browser=true
spring.application.name=diagram-viewer
server.port=${SERVER_PORT:8090}

diagrams.location=${DIAGRAMS_LOCATION:diagrams}
targets.location=${TARGETS_LOCATION:diagrams}

management.endpoints.web.exposure.include=health

kroki.container.url=${KROKI_CONTAINER_URL:http://localhost:8000}

# Database
spring.datasource.url=jdbc:postgresql://${DATASOURCE_URL:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_DATABASE_NAME:diagram-viewer-db}
spring.datasource.username=${DATASOURCE_USERNAME:user}
spring.datasource.password=${DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect