# General
vaadin.launch-browser=true
vaadin.exclude-urls=/api/domain-model/**
spring.application.name=diagram-viewer
server.port=${SERVER_PORT:8090}

# Diagrams
diagrams.location=${DIAGRAMS_LOCATION:diagrams}
targets.location=${TARGETS_LOCATION:targets}
kroki.container.url=${KROKI_CONTAINER_URL:http://localhost:8000}

# File-Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Upload JAR
jar.upload.enabled=${JAR_UPLOAD_ENABLED:false}

### Every 30 seconds
regenerateDiagramsTask.rate=${REGENERATE_DIAGRAMS_TASK_RATE:30000}

# Actuator
management.endpoints.web.exposure.include=health

# Security
okta.oauth2.issuer=${OAUTH_ISSUER:https://esentri.okta.com}
okta.oauth2.client-id=${OAUTH_CLIENT_ID:0oa1vgjp7du46YjS21d8}
okta.oauth2.redirect-uri=/authorization-code/callback

# Database
spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:diagram-viewer-db}
spring.datasource.username=${RDS_USERNAME:user}
spring.datasource.password=${RDS_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect