name: Build, Test & Deploy to AWS EB

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering for the deploy step

env:
  # Environment variables used in the script steps
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  APPLICATION_NAME: 'diagram-viewer'
  ENVIRONMENT_NAME: 'diagram-viewer-environment'
  ZIP_FILE: 'application.zip'
  VERSION_LABEL: '0.0.1-${{ github.run_number }}'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Diagram Viewer Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Bitbucket SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: |
            ${{ secrets.BITBUCKET_DIAGRAM_VIEWER_SSH_PRIVATE_KEY }}
          known_hosts: "placeholder"

      - name: Add Bitbucket to Known Hosts
        run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

      - name: Clone Bitbucket Repos
        run: |
          git clone git@bitbucket.org:esentri/nitrox-kickstart.git nitrox-kickstart
          git clone git@bitbucket.org:esentri/diagram-viewer-plugin.git diagram-viewer-plugin
          git clone git@bitbucket.org:esentri/diagram-viewer-generator-plugin.git diagram-viewer-generator-plugin

      - name: Build and Publish Local Dependencies to MavenLocal
        run: |
          cd nitrox-kickstart && ./mvnw clean install && cd ..
          cd diagram-viewer-plugin && ./gradlew publishToMavenLocal && cd ..
          cd diagram-viewer-generator-plugin && ./gradlew publishToMavenLocal && cd ..

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

