name: Build, Test & Deploy to AWS EB

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering for the deploy step

env:
  # Environment variables used in the script steps
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  APPLICATION_NAME: 'diagram-viewer'
  ENVIRONMENT_NAME: 'diagram-viewer-environment'
  ZIP_FILE: 'application.zip'
  VERSION_LABEL: '0.0.1-${{ github.run_number }}'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Diagram Viewer Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Bitbucket Nitrox-Kickstart Repo
        uses: actions/checkout@v4
        with:
          repository: git@bitbucket.org:esentri/nitrox-kickstart
          ssh-key: ${{ secrets.BITBUCKET_NITROX_KICKSTART_SSH_PRIVATE_KEY }}
          path: nitrox-kickstart

      - name: Checkout Bitbucket Diagram-Viewer-Plugin Repo
        uses: actions/checkout@v4
        with:
          repository: git@bitbucket.org:esentri/diagram-viewer-plugin
          ssh-key: ${{ secrets.BITBUCKET_DIAGRAM_VIEWER_PLUGIN_SSH_PRIVATE_KEY }}
          path: diagram-viewer-plugin

      - name: Checkout Bitbucket Diagram-Viewer-Generator-Plugin Repo
        uses: actions/checkout@v4
        with:
          repository: git@bitbucket.org:esentri/diagram-viewer-generator-plugin
          ssh-key: ${{ secrets.BITBUCKET_DIAGRAM_VIEWER_GENERATOR_PLUGIN_SSH_PRIVATE_KEY }}
          path: diagram-viewer-generator-plugin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

