name: Build, Test & Deploy to AWS EB

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_NAME: 'diagram-viewer'
  ENVIRONMENT_NAME: 'diagram-viewer-environment'
  VERSION: $VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Diagram Viewer Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Bitbucket SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: |
            ${{ secrets.BITBUCKET_DIAGRAM_VIEWER_SSH_PRIVATE_KEY }}
          known_hosts: "placeholder"

      - name: Add Bitbucket to Known Hosts
        run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

      - name: Clone Bitbucket Repos
        run: |
          git clone git@bitbucket.org:esentri/nitrox-kickstart.git nitrox-kickstart
          git clone git@bitbucket.org:esentri/diagram-viewer-plugin.git diagram-viewer-plugin
          git clone git@bitbucket.org:esentri/diagram-viewer-generator-plugin.git diagram-viewer-generator-plugin

      - name: Build and Publish Local Dependencies to MavenLocal
        run: |
          cd nitrox-kickstart && git checkout feature/roaster && mvn clean install && cd ..
          cd diagram-viewer-plugin && gradle publishToMavenLocal && cd ..
          cd diagram-viewer-generator-plugin && gradle publishToMavenLocal && cd ..

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: | 
          export TESTCONTAINERS_RYUK_DISABLED=true
          export IS_BUILD_PROFILE_INTERNAL=true
          gradle clean build -Pvaadin.productionMode

      - name: Package
        run: |
          zip -r ${{ github.run_id }}.zip .platform
          zip -j ${{ github.run_id }}.zip build/libs/diagram-viewer-0.0.1-SNAPSHOT.jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: deploy-files
          path: ${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS EB
        run: |
          aws s3 cp "deploy-files/${{ github.run_id }}.zip" s3://${{ vars.S3_BUCKET }}/artifact/diagram-viewer/
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $VERSION --description ${{ github.run_id }} --source-bundle S3Bucket="${{ vars.S3_BUCKET }}",S3Key="artifact/diagram-viewer/${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name $APPLICATION_NAME --environment-name $ENVIRONMENT_NAME --version-label $VERSION
#          aws elasticbeanstalk wait environment-updated --application-name $APPLICATION_NAME --environment-name $ENVIRONMENT_NAME --cli-read-timeout 1800 --version-label $VERSION
    
